### ISSUE TITLE
Add feature or documentation to generate gradescope token, and clarify docs

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#333]
On https://otter-grader.readthedocs.io/en/latest/otter_assign/v0/python_notebook_format.html it says: "You can also set the autograder up to automatically upload PDFs to student submissions to another Gradescope assignment by setting the necessary keys in the pdfs subkey of generate:
```
generate:
    pdfs:
    token: YOUR_GS_TOKEN   # required
    course_id: 1234        # required
    assignment_id: 5678    # required
    filtering: true        # true is the default

```

I suggest clarifying in the docs that the line "    token: YOUR_GS_TOKEN" is in fact not required.

I also suggest (per Chris Pyles' answer) including the info that a gradescope token can be generated by running the following:

```
from otter.generate.token import APIClient
​print(APIClient.get_token())
```
