### ISSUE TITLE
Speed up building R autograders on gradescope

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#543]
**Describe the bug**
Building an R autograder on gradescope takes about 25 min each time, while building one in Python takes about 5 min. There are two steps where R autograders on gradescope get stuck on for ~10 min with no additional output in the console:

Just after installing the conda packages (this takes about 3 seconds in python):
![image](https://user-images.githubusercontent.com/4560057/194715210-4cb4849c-079b-47c2-8c41-bc428addd364.png)

Just after running `apt get clean` (this takes about 2-3 minutes for python):
![image](https://user-images.githubusercontent.com/4560057/194715562-18e98528-da1c-4ea1-b85f-1f817f56fc82.png)

**To Reproduce**
Upload the example R autograder config with no additional packages to gradescope.

**Expected behavior**
Faster build times on R would be very helpful. From sample `setup.sh` in the docs it seems like several of the steps could be skipped with access to the `ucbdsinfra/otter-grader` container image. Is there any way this could be distributed and uploaded to gradescope as part of the zip file (or something along those lines), so that the wait time is less than 5 min?

It would also be great if there could be output to console during the most time-consuming steps to know what is taking such a long time.

**Versions**
3.10, 4.0.2

**Comment by joelostblom** [comment]
I realized that the delay in the first step above is due to the silent installation of R-packages in the default `requirement.R` file. Setting `overwrite_requirements=true` in the assignment config fixes this since it removes the default file and you can specify all your R packages in the `environment.yml` file instead to be installed with conda. I included all the default packages in there and the build is now 17 min. The most time-consuming step now is the installation of the `ottr` R package and the final cleanup.

It seems like my autograder is still working fine; is there any reason I should avoid doing this? If this is fine, could it be added to the docs so that it is easier to find for others?

**Comment by chrispyles** [comment]
> I realized that the delay in the first step above is due to the silent installation of R-packages in the default requirement.R file.

Yes

> From sample setup.sh in the docs it seems like several of the steps could be skipped with access to the ucbdsinfra/otter-grader container image.

I don't think it's possible with the way Gradescope's image builds work to pull in the ucbdsinfra/otter-grader image. I'd like to make the image builds faster but haven't managed a way yet because of this issue.

> Setting overwrite_requirements=true in the assignment config fixes this since it removes the default file and you can specify all your R packages in the environment.yml file instead to be installed with conda.

Yes, this is fine. If you'd like to submit a PR to update the docs I'm happy to review it. #501 is already open to convert all of otter's dependency management to conda and remove the use of `requirements.txt`/`.r` (except when provided by the user).

**Comment by joelostblom** [comment]
Great, thanks for the quick reply! I'm happy to add a note in the docs, but I'll wait until you have merged the other PR since I imagine that section of the docs might undergo some changes when the default requirements files are removed.

**Comment by chrispyles** [comment]
@joelostblom 

> Setting overwrite_requirements=true in the assignment config fixes this since it removes the default file and you can specify all your R packages in the environment.yml file instead to be installed with conda. I included all the default packages in there and the build time is now down to 14 min!

What dependencies did you add to the environment.yml to get all of these included?

**Comment by joelostblom** [comment]
It seems like all of them exist as conda packages so I added them all:

```yaml
    - r-gert
    - r-usethis
    - r-testthat
    - r-startup
    - r-rmarkdown
    - r-stringi
```

Since most of my assignments require tidyverse, I also have that in the env and haven't tried any assignments without it yet. This is the full `environment.yml` for the autograder setup I have tried on gradescope:

```yaml
name: otter-env
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - nb_conda_kernels
    - r-base>=4.1.1
    - r-essentials
    - r-devtools
    - libgit2
    - libgomp
    - r-gert
    - r-usethis
    - r-testthat
    - r-startup
    - r-rmarkdown
    - r-stringi
    - r-tidyverse
    - r-hmisc
    - pip:
        - -r requirements.txt
```

**Comment by joelostblom** [comment]
Together with this assignment config in the first notebook cell:

```
environment: environment.yml
overwrite_requirements: true
export_cell: false
check_all_cell: false
show_question_points: true
generate:
    show_hidden: true
    show_stdout: true
# and some data files here
```

**Comment by chrispyles** [comment]
I think everything here is covered in #501, so I'm going to close this issue in favor of that one, but please feel free to reopen this if I've missed anything.

**Comment by joelostblom** [comment]
I also moved my python dependencies into `environment.yml`. Here is the miminal config I cam up with in case it is helpful for anyone (note that I also use include pandas since my assignment requires it so not sure if that is a requirement even for assignments that don't use pandas directly)

```yaml
name: otter-env
channels:
    - conda-forge
    - defaults
dependencies:
    - python
    - pip
    - nb_conda_kernels
    - ipykernel
    - libgit2
    - libgomp
    - pip:
        - otter-grader==4.1.*
```
