### ISSUE TITLE
How can I autogenerate a PDF from a student submission and add it to their submission for the assignment?

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#556]
**Describe your inquiry** 
I can't figure out how to get the automatic creation and upload of the PDF to work on gradescope. This is my assignment config:

```
# ASSIGNMENT CONFIG
requirements: requirements.txt
export_cell: false
check_all_cell: false
show_question_points: true
force_public_test_summary: false
warn_missing_pdf: true
generate:
    show_hidden: true
    show_stdout: true
    token: xxxxxxxxxx
    course_id: 0000
    assignment_id: 1111
```

I have tried to upload this autograder to assignment 1111 in course 0000 with the hope that it would append a PDF to the submission so that I would both be able to see the original `.ipynb` file that students uploaded as well as the generated PDF in the same assignment. I do see a message saying `Successfully uploaded submissions for: name@email.com` in the autograder output on gradescope, but the PDF is nowhere to be found.

I thought maybe the issue was that I am trying to send the PDF to the same assignment the autograder is running from so I tried uploading the same autograder to another assignment and have it send the output to assignment 1111. This did not work either.

This is on gradescope.ca and I have tried both with my instructor account and a test student account that I created with the same result. Both the assignments I have tried with to send to have been programming assignments. Do I need to select another assignment type?
