### ISSUE TITLE
Docker grading gives empty PDFs

### ISSUE THREAD

**Issue by nibheis** [ucbds-infra/otter-grader#618]
Follow-up of BR #600.

I updated otter to version 4.3.1, cleaned all files, and I ran the `otter assign` and the `otter grade` (with --pdfs) commands - but the PDFs I get from the container are still empty (not blank PDF, they are 0 bytes).

Here is the assignment config:
```
# ASSIGNMENT CONFIG
run_tests: true
generate:
  pdfs: true
init_cell: false
files: ["figs/sketch.png"]
solutions_pdf: true
template_pdf: false
export_cell:
  pdf: true
  filtering: false
```

Local PDF generation works fine (I get the solution PDF after the assign) - but no PDF are produced on the containers during grading.

Am I missing anything?
