### ISSUE TITLE
Support adding student-created files to the submission zip with solution versions used in otter assign

### ISSUE THREAD

**Issue by aidansan** [ucbds-infra/otter-grader#737]
**Is your feature request related to a problem? Please describe.**
I would like to have the files parameter in the assignment config, use a student-created file instead of the instructor created solution file. For example, the HW assignment is for the student to have 2 files, 1 notebook file created by otter assign `hw.ipynb` and another file `math_utils.py` where the student should make a function called `softmax` the student should then import their `softmax` function from `math_utils.py` into `hw.ipynb` for use in the notebook.

**Describe the solution you'd like**
The ability for instructors to have certain Python (.py) files which they have the student to write which will use the instructor solution file when running validation in otter assign, but will use the student version of the .py file for grading.

**Describe alternatives you've considered**

**Additional context**
Putting the filename into `export_cell: files:` does not work, because the module cannot be found during validation when running `otter assign`.
e.g. 
```
# ASSIGNMENT CONFIG
solutions_pdf: true
generate: 
    pdf: true
    filtering: true
    pagebreaks: true
    zips: false
tests:
    ok_format: false
export_cell:
    files:
        - retirement.py
```
```
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Import the retirement file
# Your code here

import retirement # SOLUTION NO PROMPT
------------------


---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[5], line 4
      1 # Import the retirement file
      2 # Your code here
----> 4 import retirement # SOLUTION NO PROMPT

ModuleNotFoundError: No module named 'retirement'
```
