### ISSUE TITLE
Create more minimal examles of environment.yml files

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#739]
The `environment.yml` files for both R and Py [in the docs](https://otter-grader.readthedocs.io/en/latest/workflow/otter_generate/container_image.html#environment-yml) contain many more packages than what seems to be needed. Would it be possible to replace these with a more minimal configuration to increase clarity of what is required for otter to run? This would also make them slightly faster to build locally (about 10% in my experience with `otter grade`).

For Python

```yml
name: otter-env
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11.*
    - otter-grader=5.2.2
    - pip
```

For R

```yml
name: otter-env
channels:
    - conda-forge
    - r
    - defaults
dependencies:
  - python=3.11.*
  - pip
  - otter-grader=5.2.2
  - rpy2
  - r-base>=4.1.1
  - r-essentials
  - r-devtools
  - r-gert
  - r-usethis
  - r-testthat
  - r-startup
  - r-rmarkdown
  - r-stringi
  - r-ottr
```

I understand that some packages are optional, and maybe this could be more clearly included in the env files? For example:

```yml
name: otter-env
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - otter-grader=5.*
    - pypdf # optional; for pdf export
    - libgomp # opttonal; for ...
    - libgit2 # opttonal; for ...
    - ... # optional; for ...
```
