### ISSUE TITLE
Make the new `r-ottr` conda package compatible with R 4.1.*

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#749]
Thanks for creating https://anaconda.org/conda-forge/r-ottr @chrispyles ! This will make it more convenient to both install ottr and distribute it to students! I tried the latter but it seems like conda's R for Windows is stuck on 4.1.* due to non-trivial reasons which might take some time to resolve https://github.com/conda-forge/r-base-feedstock/issues/248.

 It seems like the CRAN package of ottr allows any version of 4.0 https://cran.r-project.org/web/packages/ottr/. Is there any chance the `ottr` conda package can accept `4.1.*` as the base R dependency instead of `>= 4.2` which is the current restriction to also make it available for windows users

**Comment by chrispyles** [comment]
@joelostblom yes ottr should be compatible with any version of R v4. Where do you see it pinned to >=4.2? The [recipe](https://github.com/conda-forge/r-ottr-feedstock/blob/main/recipe/meta.yaml) doesn't specify a version for r-base

**Comment by joelostblom** [comment]
That's odd, a few of my students who are on Windows encountered the following issue, which makes it seem like ottr require >=4.2. Reading the error message again, I realize that maybe it is the first issue of not finding base R 4.3 that leads to the second issue. I will try with a few student in class tomorrow to see if it works when we specify R =4.1 on windows

![image](https://github.com/ucbds-infra/otter-grader/assets/4560057/f5911f05-e31a-4e33-b449-d573e503c7df)

**Comment by joelostblom** [comment]
I just tried this with a student on their windows machine using `R>=4.1` and I see the same error. This is the full env file https://github.ubc.ca/MDS-2023-24/DSCI_531_viz-1_students/blob/c8cc61534ec0d4b103d9888a572a3fcf84da90b5/environment.yaml

**Comment by chrispyles** [comment]
The environment.yml file link is on a github enterprise server which I can't log in to; can you share its contents here?

It looks like there was a bot-created PR in the feedstock repo to make r-ottr compatible with r-base 4.3, but I didn't think it would make it stop accepting lower versions. https://github.com/conda-forge/r-ottr-feedstock/pull/1

**Comment by joelostblom** [comment]
My bad, here is the full env, it is quite extensive:

```yaml
name: '531'
channels:
    - conda-forge
    - r
    - defaults
dependencies:
    - python=3.11.*
    - pip
    - ipykernel
    - nb_conda_kernels
    - otter-grader=5.2.2
    - altair=5.1.2
    - vl-convert-python  # For saving altair charts as static images
    - vegafusion  # For working with charts > 5,000 graphical objects
    - vegafusion-python-embed  # Same as the previous one
    - vegafusion-jupyter  # For working with charts > 100,000 graphical objects
    - vega_datasets  # Altair example data
    - scipy
    - matplotlib
    - panel
    - r-base>=4.1
    - r-essentials
    - r-devtools
    - r-gert
    - r-usethis
    - r-testthat
    - r-startup
    - r-rmarkdown
    - r-stringi
    - r-tidyverse
    - r-hmisc
    - r-rjson
    - r-ottr
    - r-ggally
    - r-ggthemes
    - r-cowplot
    - r-irkernel
```
