### ISSUE TITLE
Hanging on ipywidgets cell

### ISSUE THREAD

**Issue by rohanjha123** [ucbds-infra/otter-grader#755]
**Describe the bug**
Otter assign hangs whenever it hits a cell using an interactive widget from ipywidgets and the command doesn't finish executing.

**To Reproduce**
Create a Python notebook with some otter tests along with the following code and try otter assigning it:
```
# ASSIGNMENT CONFIG
name: test
requirements: ../../requirements.txt
overwrite_requirements: true
template_pdf: false
solutions_pdf: true
generate:
    seed: 42
    show_stdout: true
python_version: 3.11
```
```
def say_my_name(name):
    """
    Print the current widget value in short sentence
    """
    print(f'My name is {name}')
     
interact(say_my_name, name=["James", "Bond", "James Bond"]);
```
More detailed notebooks with this issue have also been sent to Chris Pyles privately for security reasons.

**Expected behavior**
I expect the notebook to otter assign perfectly.

**Versions**
Python 3.11.0, Otter 5.1.3, more info [here](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data100/image/environment.yml)

**Additional context**
This was an issue on the data100.datahub but not on Chris' local machine.
